### ISSUE TITLE
Repeat-aft API changes (paper model and functions) to support Publisher API ingest

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#104]
api_table changes

structured text fields? (not required)
- abstract
- methods
- citations

source fields, good to have and needed to send values to plugins
- source_type (required)
- source_details (not required)

more??

**Comment by DragonWriter** [comment]
While it may depend on how it's retrieved from an api, but do we want to treat the proposed method_text, method_abstract, etc.  fields as a .txt file upload like the current document_text field or just as a large string field?

**Comment by DragonWriter** [comment]
Both potentially work for me, just want to sonsider which is more maybe more effective from a storage perspective or ease of uploading.

**Comment by DragonWriter** [comment]
Another option that may be better to consider as I think about it more is to restructure it as a single standardized JSON field like:
{"abstract": "",
"method": "",
etc.}
that could allow some additional flexibility for what sections we actually want to include.

**Comment by ejcramer** [comment]
I think the json field is a great thought and jives with the existing API patterns.
