### ISSUE TITLE
Private Fields in Variable

### ISSUE THREAD

**Issue by DragonWriter** [ripeta/repeat-aft#113]
The outputs of the machine learning are tentatively being stored as two newly added file fields in in Variable: 'nn_model' and 'tokenizer'.  These files accessed by these fields though should have restricted access from the api.  This should be either through requiring authentication at some level or from restricting its use from the api in general.  

Although currently it seems files obtained from the api don't seem to link to an accessibly location.  So if this is the case then this is maybe not a necessary change until the api properly supports reading from django file fields.

**Comment by DragonWriter** [comment]
This becomes a little more relevant now as we resolve issue #95.  
2 primary solutions are adding api-level authentication (long-term plan anyway) or excluding the fields from being read through the api (if possible).

**Comment by ejcramer** [comment]
As we extend authentication, this is at the highest level of permissions (e.g. ripetaTeam only)

**Comment by ejcramer** [comment]
The files are protected currently.  Will need to protect /variables when outside tokens are created, but outside api users can use /variabe_lists to get a list of the variables for the front end clients.
