### ISSUE TITLE
API not displaying variables and related errors

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#115]
1. When using postgresql with the latest repeat-aft.nc-test code branch, the api does not display variables even though they are in the api_table.  Also, you get an error "Variable not found" when running tests.

2. When using sqlite3, the variables display and are found with tests, but the next line is "Failed to save tokenizer to api_variable" for the tests.

I've reviewed the database structure and contents and I don't see any difference between sqlite3 and postgresql, especially close look at the api_variable table.  They both have the new nn_model and tokenizer fields setup the same.

I have recreated this scenario consistently on my local machine and on GCloud at least two times each.  See notes here:
https://docs.google.com/document/d/1uDLfPIHc2yx5Qt9fQU5vfPQHMfDGh384d1x32fTZKUw/edit?usp=sharing

NOTE: If I go back to using the repeat-aft.master, then the variables display correctly while still using postgresql.  I can't use run_mltest.py at that point because it does not exist in master.

**Comment by DragonWriter** [comment]
Aside from nn_model and tokenizer fields having been added, the only other possibly relevant change is the on_delete changes in a few foreign key fields including the variable.category.  Looking into seeing if there are perhaps some relevant compatibility issues between django and postgresql.

**Comment by ejcramer** [comment]
I think this is fine to close for now.  The only problem is on my local machine which is using postgresql 10.*  We need to keep this in mind moving forward, but I can't find any explanation or solution at the moment.

**Comment by datadiva** [comment]
We could consult with either Dan or Steven if you want. Just let me know.
