### ISSUE TITLE
Paper analysis requires one of three pdf, text, or structured_text

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#117]
It makes sense to have the "document" (PDF) required on create, 
but on update, this requirement makes it very difficult to make any changes to the other data if you have to re-upload the PDF.

We'll have to do some research to see how to do this for Django models.

**Comment by DragonWriter** [comment]
Considering not just making pdf optional, but requiring (from api viewpoint) at least one of pdf, text, or struct_text. 
Also, most recent commit as of this comment addresses accessing of files from the api, meaning the pdf file can be re-uploaded this way if necessary.

**Comment by ejcramer** [comment]
There are changes needed in repeat-aft/plugins to be sure the logic is met to require and uses one of the three.
1. - document (pdf)
2. - document_text (text)
3. - structured_text (json)

**Comment by DragonWriter** [comment]
All three are now optional as of commit e092621, although there is a check that makes sure at least one is filled.
