### ISSUE TITLE
File Upload Collision

### ISSUE THREAD

**Issue by DragonWriter** [ripeta/repeat-aft#127]
There is a potential, albeit somewhat unlikely, problem in the current model with regards to file uploads. Currently all the files upload to the following folder path: "{txt|pdf|strj}/%Y/%m/%d/", so it that it saves to a different folder depending on the date and which field it's in and copies the uploaded file's name. The problem case then is in the possibility that two files of the same type and name are uploaded the same day, the second one would overwrite the first. While this is probably unlikely to happen, there's a decent chance it'll happen at least a few times particularly with files with relatively generic names.

So I was thinking we'd want to either change the folder path to be more specific to the paper (that way it would at most only overwrite files for that paper) or change the filename to something dynamic (would likely effect article_title plugin) or a combination of the two.

**Comment by ejcramer** [comment]
Although this was a potential problem.  Django takes care of this for us.  So I'll close the issue.
