### ISSUE TITLE
Adding tags to Paper and/or Values in api (and comments eventually)

### ISSUE THREAD

**Issue by DragonWriter** [ripeta/repeat-aft#141]
Do we want to add optional comment fields to the Paper and/or Value objects, for note taking and tags.
Comments would likely be in regards to the kinds of problems faced when annotating the paper or unique characteristics about it.  For common groups of problems might be better to have set tags to filter or differentiate them. If we only want the tagging functionality it might be better to just make a tag(s) field or object for the paper. This would likely be primarily be for internal use, rather than for users to make comments about a paper.

This is related to [repeat-fore issue 38](https://github.com/ripeta/repeat-fore/issues/38), but focused on the api implementation as opposed to the the UI implementation.

**Comment by ejcramer** [comment]
Thanks for putting this in.  It can not happen until we have the api secured with access control, so I'm putting it in the icebox for now.  -elly

**Comment by DragonWriter** [comment]
Adding tags along with Model-test changes (#126) as a new queryable field in paper.

**Comment by DragonWriter** [comment]
Tags working, might reopen to address comments at a later date, post permissions updates.
