### ISSUE TITLE
authentication tests

### ISSUE THREAD

**Issue by DragonWriter** [ripeta/repeat-aft#149]
Need tests for each view with and without an access token, as well as an invalid access token. 
A test for the login url.
At least one test each with token in the header and as a query parameter.

**Comment by ejcramer** [comment]
Nick, I didn't see this repeat-aft 0.6 issue yesterday.  Could you also comment and close if it's done?  Thanks!  elly

**Comment by DragonWriter** [comment]
Existing tests in test_models and test_views were updated to account for authentication.
A new batch of tests, included in test_auth were added that test for the following:
Logging in with either a valid email or username,
Attempting to log in with an invalid password,
Using a valid authentication token in either the url or header for a view,
Using no authentictation token for a view,
Using an invalid authentication token for a view,
Using an authentication token for each view that requires one.
These new tests are run automatically in the same way that the old ones were and don't require any additional commands to run.
