### ISSUE TITLE
API authentication

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#25]
We need a way to gatekeep who can create various models in Django's database. 
 * There should be an admin/superuser role, who can create anything
 * There should be a user role, who can upload `Paper`s and `Value`s for papers they uploaded

Users should be able to register for API tokens via the API, preferably with email address verification, but this can be split into another ticket.

**Comment by ejcramer** [comment]
Related to #113

**Comment by ejcramer** [comment]
Still need to limit paper exposure by tag (e.g. CC BY vs CC BY-NC).  Tokens will be thought of per application at the api level, user applications will manage user permissions for now.

Frontend: working with tokens
Ingest: working with tokens in the ripeta API.
Still need the ingest api protected - very close and needs testing.
Extract call needs to be protected.
reviewed at meeting 2/11/19

**Comment by ejcramer** [comment]
All that's left is the protection of specifc tags (e.g. CC BY-NC).

**Comment by ejcramer** [comment]
Only thing left it protecting CC By-NC.  Nick will create an issue for that.
