### ISSUE TITLE
Integration with Postgres

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#28]
We will have to develop another `settings.py` file that uses sqlite for testing locally.

**Comment by ejcramer** [comment]
I have repeat-aft working with postgresql locally, will be applying to GCloud in the next couple of days.

**Comment by ejcramer** [comment]
I have postgresql working on GCloud, but there is an error with the unit tests due to the creation and deletion of a test db.  I'll continue troubleshooting that.  I also need to finish getting the backups working on a cronjob - issue #86.

**Comment by ejcramer** [comment]
Closing this since I have an issue for the unit test with postgres error now: #89
