### ISSUE TITLE
Handle IntegrityErrors in views

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#39]
As of right now, if a user enters two papers with the same title and authors, they get an `IntegrityError`. While we should also revisit the question of whether or not title and authors need be unique (maybe title + authors + user who created paper?), these kinds of errors should be handled, and not return a traceback.

**Comment by DragonWriter** [comment]
This should actually be resolved along with the changes outlined in issue #69.

**Comment by DragonWriter** [comment]
Resolved along with issue #69
