### ISSUE TITLE
More use-case specific documentation

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#56]
- [x] Documentation for contributors (#53) 
 - [ ] Documentation for front-end developers
 - [x] Documentation for back-end administrators
 - [x] Design documentation: clarify Domain, Category, etc.

**Comment by ejcramer** [comment]
I've updated the audience-specific documentation that Sidharthist started.  It now includes: trial/demo, along with contributing, administrators.  Still working on front-end api client consumers, but there is a placemark for it and I'll be adding it as I go.

The work Sidharthist did on concepts is very helpful.

**Comment by ejcramer** [comment]
Ok for now
