### ISSUE TITLE
Generate new SECRET_KEY on Travis and VM deployment

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#6]
We should use [this package](https://pypi.python.org/pypi/django-generate-secret-key) to generate new secret keys for every Travis run and Nixops deployment. This will put us in a better position for moving to production, where every instance will have to somehow either independent or the same secret keys.

Reference: https://docs.djangoproject.com/en/dev/topics/signing/

**Comment by ejcramer** [comment]
Since I've removed nixops as a dependency and simplified travis CI, I'm not sure this is relevant.  Closing for now.
