### ISSUE TITLE
Need "source" field for user input (Values)

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#66]
See #69 for summary of changes.

Table: api_value
Needs source and datetimes

Example current data:
http://localhost:8000/api/v0/values
[{"id":1,"value":"NCT01689519","user_entered":true,"variable":"grant_id","paper":"doi:abc"}]

**Comment by ejcramer** [comment]
Ok, so I figured out is is "values" in the api.  I should have seen that sooner, since the table is "api_value".

http://localhost:8000/api/v0/values
[{"id":1,"value":"NCT01689519","user_entered":true,"variable":"grant_id","paper":"doi:abc"}]

And once I added a user-input value, it showed up in the sqllite db.api_value.  Now I need to figure out how to do it on the client-side.

Task: This info should be added to the documentation.

**Comment by ejcramer** [comment]
Also, there is no source for the user input value, so I'm proposing that we add a field to the "api_values" model.

    source = models.TextField(**{
        "max_length": 1000,
        "help_text":
        ("Source of the user input value.  Will eventually be data from the authentication")
    })

**Comment by DragonWriter** [comment]
How exactly is it this field should be used?  I understand there is a slight overlap from user_entered.

I was thinking of the following range of inputs for the field being: "extracted" if the value was obtained from our own algorithmic plugin, "api" or "api: api_name" for if this value was obtained from an external api, and either "user: user_name" or "user_name" for if it was input by a user.  Of course, both of the first two would be entered from a plugin, but this differentiation allows for the plugin to change in function and still have that be reflected in the database.

Also, should this be a required field? As in do we want to require all input values to have an attached source. I'm inclined to say yes, but could there be any exceptions?

**Comment by ejcramer** [comment]
I like the idea of these three distinctions for values.source. IMO, I think it eliminates the need for the "user_entered" field.

I was thinking of using the user's email as the source from the front-end in case the researchers want to contact the person.  And I wonder if it should be the source api's url vs name.  I assume that would still jive with your thought process and would not require any validation?

But if we use a url for the api, I think values.source would need to be a decent sized text field, e.g. 255?

So potential values would be:
- extracted
- api:api_name or api:api_url (e.g api:http://publisher/api/blah)
- user:user_name or user:user_email (e.g. user:colin@somewhere.com)

**Comment by DragonWriter** [comment]
I agree. The main argument I can think of for keeping the user_entered field is just for easier distinction between the two output columns: plugin or user input. Though of course this still could just be acquired from the source field. Alternatively we could change the user_entered field from binary to one of "extracted", "api" or "user". Then the source field would then be either just the api_url, user_email, or either empty or something else specific for extraction.

**Comment by ejcramer** [comment]
I think that's a valid argument and agree with changing the values.user_input field to a new name (source_type?) with the three or more options, and the values.source field (not required) being used for the name, email, url, etc of the "source_type".

**Comment by DragonWriter** [comment]
Fully resolved and merged with master.  Final solution has source_type and source_detail TextFields with source_type being required as a choice between three values: api, extracted, user. The source_detail field is not required and adds additional identification information about the source that input the value into the db, such as a user's email, the api used, or version of the extraction plugin.
