### ISSUE TITLE
Write plugins for variables to extract

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#68]
Recreated variables and rewrote my draft plugin files in repeat-aft/repeat/api/analysis/plugins to match the data dictionary. I think several of them need more tweaking as they don't get any results.

**Comment by ejcramer** [comment]
Recreated variables and rewrote my draft plugin files in repeat-aft/repeat/api/analysis/plugins to match the data dictionary.  I think several of them need more tweaking as they don't get any results.

**Comment by ejcramer** [comment]
https://docs.google.com/spreadsheets/d/1quxjCi7GoBHK3efIxBZUcF2XDJPs78skNVdA2fspQj4/edit?usp=sharing

https://github.com/ripeta/Research_Reproducibility/tree/master/DataDictionary

**Comment by ejcramer** [comment]
The 12 plugins I created are breaking the unit tests.  So I put them in a separate branch for now.  See [plugins](/ripeta/repeat-aft/tree/plugins)

**Comment by ejcramer** [comment]
Two additional plugins that we need which probably should be high priority to replace api_paper fields:

article_title
article_authors

We have an article_doi working pretty well.

**Comment by DragonWriter** [comment]
For article_title and article_authors the information can be surprisingly difficult to collect without applying some machine learning.  However, they can be sometimes be easily extracted from the pdf's metadata. For example test1 returns: 
> title: Combined Vemurafenib and Cobimetinib in BRAF-Mutated Melanoma
authors: Larkin James, Ascierto Paolo A., Dréno Brigitte, Atkinson Victoria, Liszkay Gabriella, Maio Michele, Mandalà Mario, Demidov Lev, Stroyakovskiy Daniil, Thomas Luc, de la Cruz-Merino Luis, Dutriaux Caroline, Garbe Claus, Sovak Mika A., Chang Ilsung, Choong Nicholas, Hack Stephen P., McArthur Grant A., Ribas Antoni 

which is perfect; however the same functions run on test2 return:

> title: 05-14-Lam.fm
authors: None

This would have to be run differently from the existing plugins as they currently take the text as a parameter, whereas this was retrieved from the pdf.

**Comment by ejcramer** [comment]
This issue is out of date at this point and specific issues and epics belong in the repeat-plugins repo
