### ISSUE TITLE
Uploading paper should not require user input of metadata about the paper

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#69]
The paper metadata info should be extracted when the pdf is uploaded.  

The current schema requires user input for the doi, title, and author when uploading a dcument.  We need to remove these fields and use the plugins/vars to gather this data from the paper with the extraction process and store them in the *values* table ( #72 ) and add source and datetime.

----

Current *api_paper*
- unique_id (doi, etc)
- title
- authors
- document
- document_text
- domains ("core")

Recommended *api_paper* (up for discussion)
- id (auto-increment, primary key from Django)
- unique_id (not required, not primary)
- document
- document_text
- source (user upload, api ingest)*
- create_date*

(*) new or changed
-----
Current *api_value*
- value
- "matrix" numeric value (needs name)
- user_input (binary)
- variable
- paper

Recommended *api_value* (up for discussion)
- value_text*
- value_score*
- user_input (remove)
- variable
- paper
- source_type (extracted, user, api, etc)*
- source_detail*
- create_date*
- update_date*

(*) new or changed
----
Variables/plugins for paper metadata
- article_doi (Article DOI)
- article_title (Article Title)
- article_authors (List of article authors) * (or use corresponding_author)

(*) new or changed
----
I think we can hold off creating a provenance log ( #73 ) if we move the paper bibliographic (metadata) to plugin functionality ( this issue  ) and store the extracted data in the *values* table ( #72 ) with a *values.source* field and each time someone enters data is saved, we'll have a log of changes.

**Comment by DragonWriter** [comment]
As far as the api_paper changes:
Should the source be implemented similarly to what we recently agreed on in issue #66 or is just a single variable good enough?
I understand moving the title and authors fields to plugin/value dependence, but I think perhaps the domain should stay part of the paper, as the paper is assigned to a domain. 

A couple things to note on my current implementation:
- I made all the date fields, dateTime fields instead. 
- Rather than the "ricochet" prefix to the date-time fields, I just made it clear in the associated help text for the fields.

Let me know if you think some of these things should be changed.

**Comment by DragonWriter** [comment]
I also just realized that shouldn't we also be adding another field to the value table for the output, or is that being taken care of elsewhere? As in the current value.value field is for the extracted text, but shouldn't there be one as well for like the yes, no, unclear output. For example, for the clear hypothesis variable, the hypothesis found would currently be added to value.value field, but there isn't a specific field for the "yes" there was a clear hypothesis.

 I also noticed a lot of the max_values for text fields were all really large, like 10000 or even 100000 in some cases, where it makes more sense for some than others. Should we maybe be a little less liberal, or is there no problem with this?

**Comment by ejcramer** [comment]
papers.source: I think we just need a text field like values.source, but I don't feel strongly about it.

domains: We should ask the team to clarify how they envisioned papers.domains being used.  Also  taking into consideration that they don't want to have any user input when a user uploads a paper.

dateTime fields:  Totally agree, that's my database field type of choice for dates.

ricochet prefix:  Sounds good to me.

another field: **Very good catch!**  Yes, I think we need another field for a numeric result from the api plugins (re: meetings with Anthony, Colin, etc.), and I think it should be in the values table.  Langston didn't get to the scoring feature of the API and then we started reconsidering how to represent scores due to feedback from demos.  I think a new field that represents the "matrix" value goes a long way to having a numeric assessment of a variable/plugin that can be used for reports and future publisher dashboards.

max_values = In mySQL I try to keep the max_length's relative to the needs of the data and try to avoid excessive text fields unless needed. In Django, there is a difference in how max_length is enforced in the three types of text fields.  I'd need to pull a reference, but I think those textField max_length are not doing much and would need to be charField to enforce limitation.  I'm not too worried with Postgresql in terms of performance as I believe textFields and charFields are handled similarly, but not true for other dbs e.g. Oracle, MySQL. And I don't think we need to worry about portability at this time. I may do some research to verify my understanding.

- TextInput:  < 255 characters
- TextField: max_length not enforced, but can be used in form creation/validation.
- CharField: max_length enforced

**Comment by ejcramer** [comment]
Also, we don't need to delete the paper fields, we can start with making them not required.

**Comment by DragonWriter** [comment]
Okay, so for meantime I'll leave the fields in paper in, just allowing them to be blank, including domains. Will also trim the max_lengths where necessary. 
I'm fine with just the generic textField field for source.  As long as it's there we can decide how to use it at a later point.

I have a couple things regarding the models.py in general.  Is there a reason for using the ** syntax for several of the fields? It seems unnecessary to me.  And also when I looked into Django it mentioned the on_delete parameter for foreignkey fields is currently not required, though it does give a deprecation warning, though will be required in Django 2.0. So perhaps we want to add them.

**Comment by ejcramer** [comment]
"on_delete" = If they will be required with 2.0, it might be nice to add them now, but I haven't looked at how this would affect the values table. 

**options = I think it's just a semantic difference.  Did you do any "Google" research on the differences.

```
name = models.TextField(**{
    "max_length": 39,
});
```

```
name = models.TextField(max_length = 30,);
```

**Comment by ejcramer** [comment]
1. api_paper:  If you don't have a primary key, django model creates an "id" primary key auto-increment field for you automatically, and it did.  I wonder if "identifier" should be "paper_id" just for clarity?

2. api_paper: If no title or authors entered when uploading pdf on api_paper form, you get an error (see screenshot) related to lines #112-113 in models.py.  I think we can delete this chunk since we have a consistent primary key ('id) now.
```

    class Meta:
        unique_together = [("title", "authors"), ]
```
<img width="575" alt="error" src="https://user-images.githubusercontent.com/1063909/31895294-d3bbeaec-b7de-11e7-9ca0-aa5426860c03.png">


3. api_paper:  I'm not sure why, but the document_text is NOT being populated when I upload a paper with or without the past required fields filled in.

New paper upload:

```
{
    "id": 3,
    "identifier": "doi:abc",
    "document": "http://localhost:8000/api/v0/pdf/2017/10/23/test4.pdf",
    **"document_text": null,**
    "title": "Testing",
    "authors": "",
    "createdDate": "2017-10-23T14:21:44.645171Z",
    "domains": []
}
```

Previous example:
```
    {
        "unique_id": "doi:10.1056-NEJMoa1408868",
        "title": "Combined Vemurafenib and Cobimetinib in BRAF-Mutated Melanoma",
        "authors": "['James Larkin, M.D., Ph.D., Paolo A. Ascierto, M.D., Brigitte Drno, M.D., Ph.D., Victoria Atkinson, M.D.', 'Gabriella Liszkay, M.D., Michele Maio, M.D., Mario Mandal, M.D., Lev Demidov, M.D., Daniil Stroyakovskiy, M.D.', 'Luc Thomas, M.D., Ph.D., Luis de la Cruz-Merino, M.D., Caroline Dutriaux, M.D., Claus Garbe, M.D.', 'Mika A. Sovak, M.D., Ph.D., Ilsung Chang, Ph.D., Nicholas Choong, M.D., Stephen P. Hack, M.D., Ph.D.', 'Grant A. McArthur, M.B., B.S., Ph.D., and Antoni Ribas, M.D., Ph.D.']",
        "document": "http://35.185.114.189:8000/api/v0/pdf/2017/10/11/test1.pdf",
        **"document_text": "http://35.185.114.189:8000/api/v0/txt/2017/10/11/Combined_Vemurafenib_and_Cobimetinib_in_BRAF-Mutated_Melanoma.txt",**
        "domains": [
            "core"
        ]
    },
```

4.  api_value: Needs help text for api_value.value and api_value.value_output.  Help text for source_type and source_detail look good.

5. api_value: I'm wondering if we should rename "value" to "value_text" so it's clearer.  And then rename "value_output" to something like "value_score"?

**Comment by DragonWriter** [comment]
1. I intentionally used the auto-id (even made a comment on it in the
code), though we can rename it if you think it's necessary for clarity. I
renamed 'unique_id' as 'identifier', made it optional, and changed the help
text to reflect that.

2. Yeah, somehow missed that bit of code. Have deleted it locally now.

3. Not sure about that yet. Will need further looking into. I didn't
changed anything related it, so not sure why it's not working now if it was
before.

4. Okay, I'll at least try to make the help text good enough to make the
two distinct from each other.

5. I like renaming value to value_text, though am still inclined toward
value_output or value_result, as it's not really a score yet at this
point.  My understanding is that it should be a numerical code that is
variable dependent, such as: 1: yes, 2:no, 3: unclear, etc.

Also, I'm fine with meeting tomorrow at 1pm CST (2pm EST, your time).

**Comment by ejcramer** [comment]
1. Sorry I missed that comment.
2. Thanks.
3. I didn't see any obvious reason for it either.
4. Not much help text needed, just that one is extracted text value and other is numeric result maybe?
5. I prefer "value_result" slightly over "value_output", but it's fine to leave it as is.

**Comment by DragonWriter** [comment]
Fully resolved and merged with master. Final implemented solution involves the following changes:
1. Authors, title, and what was previously unique_id fields are no longer required fields for a paper to be inserted. Authors and titles still exist as fields while unique_id was renamed to identifier.
2. The primary key was changed to the default auto_id (a unique auto-increment integer field)
3. Functions that related to these fields were changed correspondingly.
Note this leaves the only required field for a paper to be the document file.
These fields that were previously required will now be stored in the values table (note each value is attached to one paper). This means these variables need to be added to the fixtures file, and have plugins added for them.  Though user input is still possible for these fields with or without associated plugins they still need to be added at a reasonably high priority, though as a separate issue.
