### ISSUE TITLE
Change paper primary key to auto-increment field 

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#71]
e.g. 10.1097/GRF.0b013e318217d60d
Note forward slash after 1097. API interprets it as a location and fails when using it as it's unique_id.

See #69 for more info.

Duplicate: ripeta/repeat-bow#6

**Comment by DragonWriter** [comment]
Fully resolved and merged with master.  Unique_id was changed to identifier and is no longer the primary key.  To replace it is the default auto_id field, which is a unique, auto-incrementing integer field. The purposes served by the unique_id are now served by various entries in the values table corresponding to variables such as article_doi.
