### ISSUE TITLE
Create data provenance table or log changes file

### ISSUE THREAD

**Issue by cynhudson** [ripeta/repeat-aft#73]
Can't find a log of changes in the database

**Comment by ejcramer** [comment]
Db table or log:
RefId of paper/plugin (user input)
Field e.g. title of paper, variable/plugin.
Who
DateTime

History of changes, not just most recent change.
How does this jive with the "values" table and sourcing those changes.

**Comment by ejcramer** [comment]
I think we can hold off on this issue if we move the paper bibliographic (metadata) to plugin functionality ( #69  ) and store the extracted data in the *values* table ( #72 ).  If we add the *values.source* field and each time someone enters data is saved, we'll have a log of changes.  I do think we need a datetime stamp on this table/model and possibly the *papers* table/model.

**Comment by ejcramer** [comment]
This is resolved with saving the extraction data to the api_value table: #72.
