### ISSUE TITLE
Travis CI failing - blocks pull request merge to master

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#76]
I changed the readme.MD and the contributors.rst files with minor changes.  Created a pull request with a new branch and it fails Travis CI checks.

It's failing on Job 203.2 which is the Mac OS build/checks.  

In looking at my original install notes that I sent to Langston, I see that xpdf did not install on it's own and I installed it manually.  I also ran into an issue with xpdf while installing on cloud services.  

I believe the build is not setup to install the needed xpf dependencies.    I'll need to recreate the issue on my local dev environment to evaluate which dependencies are missing and see if I can get this build to work automagically.

I turned off the service in github and travis site, but it still won't go through, so I'm going to delete the service for now from github and turn it back on after I can update the travis.yml file to make the Mac OS check optional.

LOG from Travis CI
/private/tmp/nix-build-qtbase-5.9.1.drv-0/qtbase-opensource-src-5.9.1/mkspecs/features/mac/default_post.prf:26: Missing closing brace(s).
building
build flags: -j1 -l1 SHELL=/nix/store/hwx5i1w9q29m2rh8i8gs2l3yk3bpz67z-bash-4.4-p12/bin/bash
cd src/ && ( test -e Makefile || /private/tmp/nix-build-qtbase-5.9.1.drv-0/qtbase-opensource-src-5.9.1/bin/qmake -o Makefile /private/tmp/nix-build-qtbase-5.9.1.drv-0/qtbase-opensource-src-5.9.1/src/src.pro ) && make -f Makefile 
/private/tmp/nix-build-qtbase-5.9.1.drv-0/qtbase-opensource-src-5.9.1/mkspecs/features/mac/default_post.prf:26: Missing closing brace(s).
Project ERROR: Unknown module(s) in QT: core gui
make: *** [Makefile:49: sub-src-make_first] Error 3
builder for ‘/nix/store/fzd7gap6gi3bn8ldvjj0yikd3w99y59a-qtbase-5.9.1.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/zrdjswwif4db3ynpimi34h004cp1hxfj-xpdf-4.00.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/zrdjswwif4db3ynpimi34h004cp1hxfj-xpdf-4.00.drv’ failed
The command "nix-env -i xpdf" failed and exited with 100 during .  <<<<<<<<<<<<<<<<<<<<

**Comment by ejcramer** [comment]
Deleting the service and turning it off did not work. It was still failing on "nix-env -i xpdf" which also  does not work on my laptop (osx). 

I finally figured out that you can turn off checks for the protected "master" here:

Settings - Branches - Protected Branches - master > edit - "Require status checks to pass before merging"

The Travis CI docs mention doing installs on osx with brew, which is how I do it. So will try with that.  I also added PYTHON_VERSION=3.3.6.

Will test and see what happens.

**Comment by siddharthist** [comment]
Yeah, `xpdf` should be installed with `homebrew` or similar on OSX. Sorry for the confusion!

**Comment by ejcramer** [comment]
I simplified the .travis.py file and tested it with the master branch.
